filelist: "/scratch16/abattle4/ashton/snp_networks/custom_l1_factorization/trait_selections/finngen_benchmark_2.studies.tsv"
pval_thresh: "1e-5"
file_ext: ".sumstats.gz"
ldscref: "/data/abattle4/aomdahl1/reference_data/eur_w_ld_chr"
#target output file:
#"ldsr_results/finngen_benchmark/summary_data/gcov_int.png"
